#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check

#upload_picture:
#  path: /api/pictures/upload
#  methods: ['POST']
#  defaults:
#    _controller: App\Controller\PictureController::uploadPicture
#    _api_resource_class: App\Enity\Picture
#    _api_item_operation_name: post_upload


